# Generated by Django 5.2.8 on 2025-12-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_heading_post_alter_postanalytics_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postanalytics',
            options={'verbose_name': 'Post Analytics', 'verbose_name_plural': 'Post Analytics'},
        ),
    ]
