# Generated by Django 5.2.8 on 2026-01-15 18:40

import apps.blog.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_postanalytics_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to=apps.blog.models.blog_thumbnail_directory),
        ),
    ]
