# Generated by Django 5.2.8 on 2026-01-28 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_thumbnail'),
        ('media', '0003_media_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_category_thumbnail', to='media.media'),
        ),
    ]
