# Generated by Django 5.2.8 on 2026-01-27 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=30)),
            ],
        ),
    ]
