# Generated by Django 5.2.8 on 2026-01-28 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_thumbnail'),
        ('media', '0002_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blog.post'),
        ),
    ]
